"""update_user_schema

Revision ID: 1e3b2f5c4b38
Revises: a3c6e7c2db43
Create Date: 2024-11-28 17:28:23.639925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3b2f5c4b38'
down_revision: Union[str, None] = 'a3c6e7c2db43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
