"""add images relationship update to user

Revision ID: 236be5ee2466
Revises: f058949a680a
Create Date: 2024-11-28 11:20:23.684289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236be5ee2466'
down_revision: Union[str, None] = 'f058949a680a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_caregiver_images', 'images', type_='foreignkey')
    op.drop_constraint('fk_pet_images', 'images', type_='foreignkey')
    op.drop_constraint('fk_user_images', 'images', type_='foreignkey')
    op.create_foreign_key('fk_user_images', 'images', 'users', ['entity_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key('fk_caregiver_images', 'images', 'caregiver_profiles', ['entity_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key('fk_pet_images', 'images', 'pets', ['entity_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pet_images', 'images', type_='foreignkey')
    op.drop_constraint('fk_caregiver_images', 'images', type_='foreignkey')
    op.drop_constraint('fk_user_images', 'images', type_='foreignkey')
    op.create_foreign_key('fk_user_images', 'images', 'users', ['entity_id'], ['id'])
    op.create_foreign_key('fk_pet_images', 'images', 'pets', ['entity_id'], ['id'])
    op.create_foreign_key('fk_caregiver_images', 'images', 'caregiver_profiles', ['entity_id'], ['id'])
    # ### end Alembic commands ###
